apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-deployment
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Release.Name }}
          image: {{ .Values.image.tag }}
          ports:
            - containerPort: {{ .Values.env.port }}
              protocol: "UDP"
          volumeMounts:
            - name: server-settings
              mountPath: "/opt/factorio/data"
            - name: saves
              mountPath: "/opt/factorio/saves"
      volumes:
        - name: server-settings
          configMap:
            name: {{ .Release.Name }}-server-settings
        - name: saves
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-saves-vol-claim
      imagePullSecrets:
        - name: docker-registry-creds
