apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-service
spec:
  type: NodePort
  selector:
    app: {{ .Release.Name }}
  ports:
    - port: 80
      protocol: "UDP"
      targetPort: {{ .Values.env.port }}
      nodePort: {{ .Values.nodePort }}
